// Centralized enums & collection names — import these everywhere, never inline strings.

const COLLECTIONS = {
  USERS: "users",
  ADDRESSES: "addresses", // subcollection under users/{uid}
  CATEGORIES: "categories",
  PRODUCTS: "products",
  BANNERS: "banners",
  OFFERS: "offers",
  CARTS: "carts",
  ORDERS: "orders",
  DELIVERY_PARTNERS: "deliveryPartners",
  CONFIG: "config",
  METRICS: "metrics",
};

const ORDER_STATUS = {
  PLACED: "ORDER_PLACED",
  ACCEPTED: "ORDER_ACCEPTED",
  PACKING: "PACKING",
  READY: "READY_FOR_DELIVERY",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
};

const ORDER_STATUS_FLOW = [
  ORDER_STATUS.PLACED,
  ORDER_STATUS.ACCEPTED,
  ORDER_STATUS.PACKING,
  ORDER_STATUS.READY,
  ORDER_STATUS.OUT_FOR_DELIVERY,
  ORDER_STATUS.DELIVERED,
];

const PAYMENT_METHOD = { COD: "COD", UPI: "UPI", RAZORPAY: "RAZORPAY" };
const PAYMENT_STATUS = { PENDING: "PENDING", PAID: "PAID", FAILED: "FAILED" };

const AVAILABILITY = {
  AVAILABLE: "AVAILABLE",
  UNAVAILABLE_TODAY: "UNAVAILABLE_TODAY",
  OUT_OF_STOCK: "OUT_OF_STOCK",
};

const STOCK_LEVEL = { IN_STOCK: "IN_STOCK", LOW_STOCK: "LOW_STOCK", OUT_OF_STOCK: "OUT_OF_STOCK" };
const LOW_STOCK_THRESHOLD = 10;

const OFFER_KIND = { PERCENT: "PERCENT", FLAT: "FLAT" };
const OFFER_SCOPE = { CART: "CART", CATEGORY: "CATEGORY", PRODUCT: "PRODUCT" };

const ROLES = { CUSTOMER: "CUSTOMER", ADMIN: "ADMIN", PARTNER: "PARTNER" };

module.exports = {
  COLLECTIONS,
  ORDER_STATUS,
  ORDER_STATUS_FLOW,
  PAYMENT_METHOD,
  PAYMENT_STATUS,
  AVAILABILITY,
  STOCK_LEVEL,
  LOW_STOCK_THRESHOLD,
  OFFER_KIND,
  OFFER_SCOPE,
  ROLES,
};
